### ISSUE TITLE
Hyperbox Client can't connect to hypervisor

### ISSUE THREAD

**Issue by devrando** [hyperbox/hyperbox#16]
If I wan't to connect to Hypervisor(Server Debian 8), client shows following errors:
Result: No Hypervisor are selectable.

```
01:05 ERROR: [kryonet] Error updating connection: Connection 4
com.esotericsoftware.kryonet.KryoNetException: Error during deserialization.
	at com.esotericsoftware.kryonet.TcpConnection.readObject(TcpConnection.java:159)
	at com.esotericsoftware.kryonet.Client.update(Client.java:273)
	at com.esotericsoftware.kryonet.Client.run(Client.java:356)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: -1330341840
Serialization trace:
time (io.kamax.hbox.comm.Answer)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:119)
	at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:644)
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:99)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:482)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:767)
	at com.esotericsoftware.kryonet.KryoSerialization.read(KryoSerialization.java:73)
	at com.esotericsoftware.kryonet.TcpConnection.readObject(TcpConnection.java:157)
	... 3 more
01:05  INFO: [kryonet] Connection 4 disconnected.
Exception in thread "Client" com.esotericsoftware.kryonet.KryoNetException: Error during deserialization.
	at com.esotericsoftware.kryonet.TcpConnection.readObject(TcpConnection.java:159)
	at com.esotericsoftware.kryonet.Client.update(Client.java:273)
	at com.esotericsoftware.kryonet.Client.run(Client.java:356)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: -1330341840
Serialization trace:
time (io.kamax.hbox.comm.Answer)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:119)
	at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:644)
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:99)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:482)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:767)
	at com.esotericsoftware.kryonet.KryoSerialization.read(KryoSerialization.java:73)
	at com.esotericsoftware.kryonet.TcpConnection.readObject(TcpConnection.java:157)
	... 3 more
01:38  INFO: [kryonet] Connecting: /10.1.1.37:45612
01:38  INFO: [kryonet] Connection 5 connected: /10.1.1.37
01:40 ERROR: [kryonet] Error updating connection: Connection 5
com.esotericsoftware.kryonet.KryoNetException: Error during deserialization.
	at com.esotericsoftware.kryonet.TcpConnection.readObject(TcpConnection.java:159)
	at com.esotericsoftware.kryonet.Client.update(Client.java:273)
	at com.esotericsoftware.kryonet.Client.run(Client.java:356)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: -1330341564
Serialization trace:
time (io.kamax.hbox.comm.Answer)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:119)
	at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:644)
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:99)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:482)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:767)
	at com.esotericsoftware.kryonet.KryoSerialization.read(KryoSerialization.java:73)
	at com.esotericsoftware.kryonet.TcpConnection.readObject(TcpConnection.java:157)
	... 3 more
01:40  INFO: [kryonet] Connection 5 disconnected.
Exception in thread "Client" com.esotericsoftware.kryonet.KryoNetException: Error during deserialization.
	at com.esotericsoftware.kryonet.TcpConnection.readObject(TcpConnection.java:159)
	at com.esotericsoftware.kryonet.Client.update(Client.java:273)
	at com.esotericsoftware.kryonet.Client.run(Client.java:356)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: -1330341564
Serialization trace:
time (io.kamax.hbox.comm.Answer)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:119)
	at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:644)
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:99)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:482)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:767)
	at com.esotericsoftware.kryonet.KryoSerialization.read(KryoSerialization.java:73)
	at com.esotericsoftware.kryonet.TcpConnection.readObject(TcpConnection.java:157)
	... 3 more
03:56  INFO: [kryonet] Connecting: /10.1.1.37:45612
04:00  INFO: [kryonet] Connecting: /10.1.1.37:45612
04:00  INFO: [kryonet] Connection 1 connected: /10.1.1.37
04:05 ERROR: [kryonet] Error updating connection: Connection 1
com.esotericsoftware.kryonet.KryoNetException: Error during deserialization.
	at com.esotericsoftware.kryonet.TcpConnection.readObject(TcpConnection.java:159)
	at com.esotericsoftware.kryonet.Client.update(Client.java:273)
	at com.esotericsoftware.kryonet.Client.run(Client.java:356)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: -1330340434
Serialization trace:
time (io.kamax.hbox.comm.Answer)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:119)
	at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:644)
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:99)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:482)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:767)
	at com.esotericsoftware.kryonet.KryoSerialization.read(KryoSerialization.java:73)
	at com.esotericsoftware.kryonet.TcpConnection.readObject(TcpConnection.java:157)
	... 3 more
04:05  INFO: [kryonet] Connection 1 disconnected.
Exception in thread "Client" com.esotericsoftware.kryonet.KryoNetException: Error during deserialization.
	at com.esotericsoftware.kryonet.TcpConnection.readObject(TcpConnection.java:159)
	at com.esotericsoftware.kryonet.Client.update(Client.java:273)
	at com.esotericsoftware.kryonet.Client.run(Client.java:356)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: -1330340434
Serialization trace:
time (io.kamax.hbox.comm.Answer)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:119)
	at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:644)
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:99)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:482)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:767)
	at com.esotericsoftware.kryonet.KryoSerialization.read(KryoSerialization.java:73)
	at com.esotericsoftware.kryonet.TcpConnection.readObject(TcpConnection.java:157)
	... 3 more
^Cmac-x230:hbox bastian$ /Users/bastian/Downloads/hbox/hyperbox 
00:00  INFO: [kryonet] Connecting: /10.1.1.37:45612
00:00  INFO: [kryonet] Connection 2 connected: /10.1.1.37
00:03 ERROR: [kryonet] Error updating connection: Connection 2
com.esotericsoftware.kryonet.KryoNetException: Error during deserialization.
	at com.esotericsoftware.kryonet.TcpConnection.readObject(TcpConnection.java:159)
	at com.esotericsoftware.kryonet.Client.update(Client.java:273)
	at com.esotericsoftware.kryonet.Client.run(Client.java:356)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: -1330338463
Serialization trace:
time (io.kamax.hbox.comm.Answer)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:119)
	at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:644)
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:99)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:482)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:767)
	at com.esotericsoftware.kryonet.KryoSerialization.read(KryoSerialization.java:73)
	at com.esotericsoftware.kryonet.TcpConnection.readObject(TcpConnection.java:157)
	... 3 more
00:03  INFO: [kryonet] Connection 2 disconnected.
Exception in thread "Client" com.esotericsoftware.kryonet.KryoNetException: Error during deserialization.
	at com.esotericsoftware.kryonet.TcpConnection.readObject(TcpConnection.java:159)
	at com.esotericsoftware.kryonet.Client.update(Client.java:273)
	at com.esotericsoftware.kryonet.Client.run(Client.java:356)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: -1330338463
Serialization trace:
time (io.kamax.hbox.comm.Answer)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:119)
	at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:644)
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:99)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:482)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:767)
	at com.esotericsoftware.kryonet.KryoSerialization.read(KryoSerialization.java:73)
	at com.esotericsoftware.kryonet.TcpConnection.readObject(TcpConnection.java:157)
	... 3 more
00:26  INFO: [kryonet] Connecting: /10.1.1.37:45612
00:26  INFO: [kryonet] Connection 3 connected: /10.1.1.37
00:29 ERROR: [kryonet] Error updating connection: Connection 3
com.esotericsoftware.kryonet.KryoNetException: Error during deserialization.
	at com.esotericsoftware.kryonet.TcpConnection.readObject(TcpConnection.java:159)
	at com.esotericsoftware.kryonet.Client.update(Client.java:273)
	at com.esotericsoftware.kryonet.Client.run(Client.java:356)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: -1330338261
Serialization trace:
time (io.kamax.hbox.comm.Answer)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:119)
	at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:644)
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:99)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:482)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:767)
	at com.esotericsoftware.kryonet.KryoSerialization.read(KryoSerialization.java:73)
	at com.esotericsoftware.kryonet.TcpConnection.readObject(TcpConnection.java:157)
	... 3 more
00:29  INFO: [kryonet] Connection 3 disconnected.
Exception in thread "Client" com.esotericsoftware.kryonet.KryoNetException: Error during deserialization.
	at com.esotericsoftware.kryonet.TcpConnection.readObject(TcpConnection.java:159)
	at com.esotericsoftware.kryonet.Client.update(Client.java:273)
	at com.esotericsoftware.kryonet.Client.run(Client.java:356)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: -1330338261
Serialization trace:
time (io.kamax.hbox.comm.Answer)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:119)
	at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:644)
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:99)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:482)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:767)
	at com.esotericsoftware.kryonet.KryoSerialization.read(KryoSerialization.java:73)
	at com.esotericsoftware.kryonet.TcpConnection.readObject(TcpConnection.java:157)
	... 3 more

```

![image](https://cloud.githubusercontent.com/assets/18743394/20240848/49c6a176-a923-11e6-9caf-62e8ffab0e49.png)

**Comment by maxidor** [comment]
This typically happen if the client and server version are not matching. Can you double check please?

**Comment by maxidor** [comment]
Closing due to lack of feedback
