### ISSUE TITLE
can't connect to hyperbox

### ISSUE THREAD

**Issue by boistordu** [hyperbox/hyperbox#4]
Hi,
last version + win10
still no connection and no logs folder... Do you have any idea?

**Comment by boistordu** [comment]
Microsoft Windows [Version 10.0.10240]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\Users\charles-guillaume>ping -6 fe80::da50:e6ff:fea8:6f80

Pinging fe80::da50:e6ff:fea8:6f80 with 32 bytes of data:
Reply from fe80::da50:e6ff:fea8:6f80: time=2ms
Reply from fe80::da50:e6ff:fea8:6f80: time=1ms
Reply from fe80::da50:e6ff:fea8:6f80: time<1ms
Reply from fe80::da50:e6ff:fea8:6f80: time<1ms

Ping statistics for fe80::da50:e6ff:fea8:6f80:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 2ms, Average = 0ms

C:\Users\charles-guillaume>ping -6 fe80::da50:e6ff:fea8:6f80

Pinging fe80::da50:e6ff:fea8:6f80 with 32 bytes of data:
Reply from fe80::da50:e6ff:fea8:6f80: time<1ms
Reply from fe80::da50:e6ff:fea8:6f80: time<1ms
Reply from fe80::da50:e6ff:fea8:6f80: time<1ms
Reply from fe80::da50:e6ff:fea8:6f80: time=1ms

Ping statistics for fe80::da50:e6ff:fea8:6f80:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 1ms, Average = 0ms

C:\Users\charles-guillaume>ping -6 fe80::da50:e6ff:fea8:6f80

Pinging fe80::da50:e6ff:fea8:6f80 with 32 bytes of data:
Reply from fe80::da50:e6ff:fea8:6f80: time=1ms
Reply from fe80::da50:e6ff:fea8:6f80: time=1ms
Reply from fe80::da50:e6ff:fea8:6f80: time=2ms
Reply from fe80::da50:e6ff:fea8:6f80: time<1ms

Ping statistics for fe80::da50:e6ff:fea8:6f80:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 2ms, Average = 1ms

C:\Users\charles-guillaume>ping -6 fe80::da50:e6ff:fea8:6f80

Pinging fe80::da50:e6ff:fea8:6f80 with 32 bytes of data:
Reply from fe80::da50:e6ff:fea8:6f80: time=1ms
Reply from fe80::da50:e6ff:fea8:6f80: time=1ms
Reply from fe80::da50:e6ff:fea8:6f80: time<1ms
Reply from fe80::da50:e6ff:fea8:6f80: time=10ms

Ping statistics for fe80::da50:e6ff:fea8:6f80:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 10ms, Average = 3ms

C:\Users\charles-guillaume>ping -6 fe80::da50:e6ff:fea8:6f80

Pinging fe80::da50:e6ff:fea8:6f80 with 32 bytes of data:
Reply from fe80::da50:e6ff:fea8:6f80: time=1ms
Reply from fe80::da50:e6ff:fea8:6f80: time=1ms
Reply from fe80::da50:e6ff:fea8:6f80: time=2ms
Reply from fe80::da50:e6ff:fea8:6f80: time=6ms

Ping statistics for fe80::da50:e6ff:fea8:6f80:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 1ms, Maximum = 6ms, Average = 2ms

C:\Users\charles-guillaume>tracert -6 fe80::da50:e6ff:fea8:6f80

Tracing route to fe80::da50:e6ff:fea8:6f80 over a maximum of 30 hops

  1     4 ms    30 ms    21 ms  fe80::da50:e6ff:fea8:6f80

Trace complete.

C:\Users\charles-guillaume>tracert 192.168.5.1

Tracing route to alpha.ada.is-a-geek.org [192.168.5.1]
over a maximum of 30 hops:

  1    <1 ms    <1 ms    <1 ms  alpha.ada.is-a-geek.org [192.168.5.1]

Trace complete.

C:\Users\charles-guillaume>tracert -6 fe80::da50:e6ff:fea8:6f80

Tracing route to fe80::da50:e6ff:fea8:6f80 over a maximum of 30 hops

  1    <1 ms    <1 ms    <1 ms  fe80::da50:e6ff:fea8:6f80

Trace complete.

C:\Users\charles-guillaume>tracert 192.168.5.1

Tracing route to alpha.ada.is-a-geek.org [192.168.5.1]
over a maximum of 30 hops:

  1    <1 ms     1 ms     1 ms  alpha.ada.is-a-geek.org [192.168.5.1]

Trace complete.

C:\Users\charles-guillaume>c:

C:\Users\charles-guillaume>cd c:
C:\Users\charles-guillaume

C:\Users\charles-guillaume>cd ..

C:\Users>cd ..

C:\>cd "Program Files"

C:\Program Files>cd Hyperbox

C:\Program Files\Hyperbox>Server
'Server' is not recognized as an internal or external command,
operable program or batch file.

C:\Program Files\Hyperbox>cd Server

C:\Program Files\Hyperbox\Server>hyperbox.exe
Hyperbox 0.0.11 - Java 1.8.0_60 Java HotSpot(TM) 64-Bit Server VM 25.60-b23 - Wi
ndows 10 10.0 amd64
2015.09.19-16:22:54.501 |      Info | Hyperbox Init Sequence started
2015.09.19-16:22:56.340 |     Error | io.kamax.hbox.exception.HyperboxException:
 Unable to get H2 connection
2015.09.19-16:22:56.341 | Exception | main | Controller
io.kamax.hbox.exception.HyperboxException: Unable to get H2 connection
        at io.kamax.hboxd.persistence.sql.h2.H2SqlPersistor.getConn(H2SqlPersist
or.java:97)
        at io.kamax.hboxd.persistence.sql.StoreSQL.createTables(StoreSQL.java:42
)
        at io.kamax.hboxd.persistence.sql.StoreSQL.init(StoreSQL.java:37)
        at io.kamax.hboxd.persistence.sql.SqlPersistor.start(SqlPersistor.java:4
81)
        at io.kamax.hboxd.core.SingleHostServer.start(SingleHostServer.java:164)

        at io.kamax.hboxd.controller.Controller.startBack(Controller.java:80)
        at io.kamax.hboxd.controller.Controller.start(Controller.java:157)
        at io.kamax.hboxd.HyperboxInteractive.main(HyperboxInteractive.java:34)
Caused by: org.h2.jdbc.JdbcSQLException: Error while creating file "C:/Program F
iles/Hyperbox/Server/data" [90062-174]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
        at org.h2.message.DbException.get(DbException.java:172)
        at org.h2.message.DbException.get(DbException.java:149)
        at org.h2.store.fs.FilePathDisk.createDirectory(FilePathDisk.java:262)
        at org.h2.store.fs.FileUtils.createDirectory(FileUtils.java:43)
        at org.h2.store.fs.FileUtils.createDirectories(FileUtils.java:296)
        at org.h2.store.FileLock.lockFile(FileLock.java:340)
        at org.h2.store.FileLock.lock(FileLock.java:133)
        at org.h2.engine.Database.open(Database.java:575)
        at org.h2.engine.Database.openDatabase(Database.java:236)
        at org.h2.engine.Database.<init>(Database.java:231)
        at org.h2.engine.Engine.openSession(Engine.java:56)
        at org.h2.engine.Engine.openSession(Engine.java:160)
        at org.h2.engine.Engine.createSessionAndValidate(Engine.java:139)
        at org.h2.engine.Engine.createSession(Engine.java:122)
        at org.h2.engine.Engine.createSession(Engine.java:28)
        at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.jav
a:323)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:105)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
        at org.h2.Driver.connect(Driver.java:73)
        at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:187
)
        at org.h2.jdbcx.JdbcDataSource.getConnection(JdbcDataSource.java:161)
        at io.kamax.hboxd.persistence.sql.h2.H2SqlPersistor.getConn(H2SqlPersist
or.java:93)
        ... 7 more
2015.09.19-16:22:56.354 |      Info | -------> Hyperbox is stopping <-------
2015.09.19-16:22:56.355 |      Info | Stopping front-ends
2015.09.19-16:22:56.361 |      Info | Finished stopping front-ends
2015.09.19-16:22:56.361 |      Info | Stopping back-ends
2015.09.19-16:22:56.363 |      Info | Finished stopping back-ends
2015.09.19-16:22:56.364 |      Info | -------> Hyperbox halt <-------

C:\Program Files\Hyperbox\Server>

**Comment by boistordu** [comment]
by the way, there is no service registered as hyperbox in my windows services.msc

**Comment by maxidor** [comment]
I haven't looked at Windows 10 yet, but it seems the breakage you see is big. I'll investigate next week.
About the service, it was broken already but did not work on that issue yet. Will have a look at it next week also.
Stay tuned!

**Comment by boistordu** [comment]
thanks mate... because your solution would really help me to administrate my secondary server.

Envoyé à partir d'Outlook




On Sat, Sep 19, 2015 at 9:23 AM -0700, "Maxime Dor" <notifications@github.com> wrote:
I haven't looked at Windows 10 yet, but it seems the breakage you see is big. I'll investigate next week.
About the service, it was broken already but did not work on that issue yet. Will have a look at it next week also.
Stay tuned!

---

**Comment by maxidor** [comment]
Should be fixed in [0.0.12](https://github.com/hyperbox/hyperbox/releases/tag/0.0.12).
Reopen this issue if this is not the case.
