### ISSUE TITLE
Client doesn't start on Fedora 29

### ISSUE THREAD

**Issue by FedgeNo** [hyperbox/hyperbox#42]
I installed Java with dnf install java and then installed the client with the run file provided on here. Nothing happens when I click the icon in the applications menu

**Comment by FedgeNo** [comment]
Found where the executable ended up and ran it from the command line. It dumped this: 

Cannot use GUI, headless environment detected
java.awt.HeadlessException
	at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
	at java.awt.Window.<init>(Window.java:536)
	at java.awt.Frame.<init>(Frame.java:420)
	at javax.swing.JFrame.<init>(JFrame.java:233)
	at io.kamax.hboxc.gui.MainView.<init>(MainView.java:62)
	at io.kamax.hboxc.gui.Gui$1.run(Gui.java:76)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at io.kamax.hboxc.gui.Gui$EventQueueProxy.dispatchEvent(Gui.java:170)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by maxidorius** [comment]
```
Cannot use GUI, headless environment detected
```
Is your problem. Make sure you are running Java 8 and a supported Display Manager.

**Comment by FedgeNo** [comment]
Problem was solved by installing java-1.8.0-openjdk
I guess that's a thing on Fedora recently that just doing dnf install java gives you a headless install
