### ISSUE TITLE
Can't connect to hypervisor

### ISSUE THREAD

**Issue by algare** [hyperbox/hyperbox#52]
Connection to hypervisor (6.1): "Failed". End of log file:
```
2021.03.19-11:44:39.292 |   Warning | Accessing Gui::coreReader on EDIT!
java.lang.Exception
        at io.kamax.hboxc.gui.Gui.getReader(Gui.java:214)
        at io.kamax.hboxc.gui.ServerMachineView.updateServer(ServerMachineView.java:414)
        at io.kamax.hboxc.gui.ServerMachineView.putHypervisorConnectionStateEvent(ServerMachineView.java:282)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at net.engio.mbassy.dispatch.ReflectiveHandlerInvocation.invokeHandler(ReflectiveHandlerInvocation.java:23)
        at net.engio.mbassy.dispatch.ReflectiveHandlerInvocation.invoke(ReflectiveHandlerInvocation.java:49)
        at net.engio.mbassy.dispatch.MessageDispatcher.dispatch(MessageDispatcher.java:30)
        at net.engio.mbassy.subscription.Subscription.publish(Subscription.java:73)
        at net.engio.mbassy.bus.MessagePublication.execute(MessagePublication.java:43)
        at net.engio.mbassy.bus.MBassador.publish(MBassador.java:36)
        at io.kamax.hboxc.event.DefaultEventManager.send(DefaultEventManager.java:137)
        at io.kamax.hboxc.gui.GuiEventManager.access$000(GuiEventManager.java:29)
        at io.kamax.hboxc.gui.GuiEventManager$1.run(GuiEventManager.java:48)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at io.kamax.hboxc.gui.Gui$EventQueueProxy.dispatchEvent(Gui.java:170)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
2021.03.19-11:44:39.293 |   Warning | Accessing Gui::coreReader on EDIT!
java.lang.Exception
        at io.kamax.hboxc.gui.Gui.getReader(Gui.java:214)
        at io.kamax.hboxc.gui.connector.ConnectorDetailedView.putHypervisorStateEvent(ConnectorDetailedView.java:176)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at net.engio.mbassy.dispatch.ReflectiveHandlerInvocation.invokeHandler(ReflectiveHandlerInvocation.java:23)
        at net.engio.mbassy.dispatch.ReflectiveHandlerInvocation.invoke(ReflectiveHandlerInvocation.java:49)
        at net.engio.mbassy.dispatch.MessageDispatcher.dispatch(MessageDispatcher.java:30)
        at net.engio.mbassy.subscription.Subscription.publish(Subscription.java:73)
        at net.engio.mbassy.bus.MessagePublication.execute(MessagePublication.java:43)
        at net.engio.mbassy.bus.MBassador.publish(MBassador.java:36)
        at io.kamax.hboxc.event.DefaultEventManager.send(DefaultEventManager.java:137)
        at io.kamax.hboxc.gui.GuiEventManager.access$000(GuiEventManager.java:29)
        at io.kamax.hboxc.gui.GuiEventManager$1.run(GuiEventManager.java:48)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at io.kamax.hboxc.gui.Gui$EventQueueProxy.dispatchEvent(Gui.java:170)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by maxidorius** [comment]
Thank you for the report! These are just warning and are not related to the issue - Could you attach the full log file or put it somewhere please?

**Comment by algare** [comment]
[hbox.log](https://github.com/hyperbox/hyperbox/files/6173024/hbox.log)
[hbox_1.log](https://github.com/hyperbox/hyperbox/files/6173025/hbox_1.log)

**Comment by maxidorius** [comment]
Nothing wrong on the client side, seems like the disconnection is either coming from the server or from your network equipement. Can you also put the server's log for a disconnection?
