### ISSUE TITLE
NULL message when attempting hypervisor -> connect

### ISSUE THREAD

**Issue by MudDev** [hyperbox/hyperbox#57]
Hello, I'm not able to connect to my remote server using the hyperbox client UI.. 

My vbox configuration? It's all default from a fresh ubuntu install, running **VirtualBox web service 6.1.26**:
>/usr/bin/vboxwebsrv --pidfile /run/vboxweb/vboxweb.pid --host=xxx.xxx.xxx.xxx --background

#### Here are screen shot of the steps I take to get the error after I choose **Hypervisor -> Connect** on the UI

![image](https://user-images.githubusercontent.com/44410798/152169164-6c921cf7-e579-449b-99ee-74ec266a58ae.png)

After clicking connect here, I get this dialog:
![image](https://user-images.githubusercontent.com/44410798/152169267-39cda78b-2b87-4329-8c5d-bd8457ade28f.png)

On the server, I am using virtualbox 6.1
**Oracle VM VirtualBox VM Selector v6.1.26_Ubuntu**

I installed server hyperbox-0.0.17 (_server_0.0.17_all.deb_)

## Server Logs:
```
Feb 02 14:06:42 vmhost hboxd[3749]: [Server] DEBUG [app]d.front.kryonet.KryonetServerFront - Received request from 4 (xxx.xxx.xxx.xxx:60882) : 1645678705069 - HBOX - HypervisorList
Feb 02 14:06:42 vmhost hboxd[3749]: [Server] DEBUG [app]d.session.SessionManager - Received Request from xxx.xxx.xxx.xxx:60882
Feb 02 14:06:42 vmhost hboxd[3749]: [SessWT - Session #1643808766703 - Connection #4] INFO [app]d.task.TaskManager - Received Request #1645678705069 [HBOX:HypervisorList] from Client #4 (xxx.xxx.xxx.xxx:60882) under admin
Feb 02 14:06:42 vmhost hboxd[3749]: [SessWT - Session #1643808766703 - Connection #4] DEBUG [app]d.core.DefaultActionManager - Found HypervisorList for HBOXHypervisorList
Feb 02 14:06:42 vmhost hboxd[3749]: [SessWT - Session #1643808766703 - Connection #4] INFO [app]d.task.TaskManager - Immediate execute of Request #1645678705069 [HBOX:HypervisorList]
Feb 02 14:06:42 vmhost hboxd[3749]: [SessWT - Session #1643808766703 - Connection #4] INFO [app]d.task.TaskManager - Processing Request #1645678705069
Feb 02 14:06:42 vmhost hboxd[3749]: [SessWT - Session #1643808766703 - Connection #4] INFO [app]d.task.TaskManager - Request #1645678705069 [HBOX:HypervisorList] succeeded.
```

## CLIENT LOGS
```
[SwingWorker-pool-8-thread-1] ERROR [app]c.controller.Controller - Unable to perform the request [ HypervisorConnect ]
[Core-EvMgr] INFO [app]c.core.server.CachedServerReader - Clearing cache for server io.kamax.hboxc.core.server.CachedServerReader@25a4568f[id=27651278-6f27-4bf9-aa87-c60d5db08ece|name=vmhost]
io.kamax.hbox.exception.HyperboxException
        at io.kamax.hboxc.core.server.Server.sendRequest(Server.java:144)
        at io.kamax.hboxc.core.server.Server.sendRequest(Server.java:132)
        at io.kamax.hboxc.controller.Controller.post(Controller.java:163)
        at io.kamax.hboxc.gui.workers.MessageWorker.innerDoInBackground(MessageWorker.java:42)
        at io.kamax.hboxc.gui.workers.MessageWorker.innerDoInBackground(MessageWorker.java:31)
        at io.kamax.hboxc.gui.utils.AxSwingWorker.doInBackground(AxSwingWorker.java:71)
        at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
[AWT-EventQueue-0] WARN [app]c.gui.Gui - Accessing Gui::coreReader on EDIT!
java.lang.Exception
        at io.kamax.hboxc.gui.Gui.getReader(Gui.java:218)
        at io.kamax.hboxc.gui.ServerMachineView.updateServer(ServerMachineView.java:418)
        at io.kamax.hboxc.gui.ServerMachineView.putHypervisorConnectionStateEvent(ServerMachineView.java:286)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at net.engio.mbassy.dispatch.ReflectiveHandlerInvocation.invokeHandler(ReflectiveHandlerInvocation.java:23)
        at net.engio.mbassy.dispatch.ReflectiveHandlerInvocation.invoke(ReflectiveHandlerInvocation.java:49)
        at net.engio.mbassy.dispatch.MessageDispatcher.dispatch(MessageDispatcher.java:30)
        at net.engio.mbassy.subscription.Subscription.publish(Subscription.java:73)
        at net.engio.mbassy.bus.MessagePublication.execute(MessagePublication.java:43)
        at net.engio.mbassy.bus.MBassador.publish(MBassador.java:36)
        at io.kamax.hboxc.event.DefaultEventManager.send(DefaultEventManager.java:141)
        at io.kamax.hboxc.gui.GuiEventManager.access$000(GuiEventManager.java:29)
        at io.kamax.hboxc.gui.GuiEventManager$1.run(GuiEventManager.java:48)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at io.kamax.hboxc.gui.Gui$EventQueueProxy.dispatchEvent(Gui.java:174)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
[AWT-EventQueue-0] WARN [app]c.gui.Gui - Accessing Gui::coreReader on EDIT!
java.lang.Exception
        at io.kamax.hboxc.gui.Gui.getReader(Gui.java:218)
        at io.kamax.hboxc.gui.connector.ConnectorDetailedView.putHypervisorStateEvent(ConnectorDetailedView.java:170)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at net.engio.mbassy.dispatch.ReflectiveHandlerInvocation.invokeHandler(ReflectiveHandlerInvocation.java:23)
        at net.engio.mbassy.dispatch.ReflectiveHandlerInvocation.invoke(ReflectiveHandlerInvocation.java:49)
        at net.engio.mbassy.dispatch.MessageDispatcher.dispatch(MessageDispatcher.java:30)
        at net.engio.mbassy.subscription.Subscription.publish(Subscription.java:73)
        at net.engio.mbassy.bus.MessagePublication.execute(MessagePublication.java:43)
        at net.engio.mbassy.bus.MBassador.publish(MBassador.java:36)
        at io.kamax.hboxc.event.DefaultEventManager.send(DefaultEventManager.java:141)
        at io.kamax.hboxc.gui.GuiEventManager.access$000(GuiEventManager.java:29)
        at io.kamax.hboxc.gui.GuiEventManager$1.run(GuiEventManager.java:48)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at io.kamax.hboxc.gui.Gui$EventQueueProxy.dispatchEvent(Gui.java:174)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by maxidorius** [comment]
Thanks for the report! Can you also confirm you are using the v0.0.17 client?

**Comment by MudDev** [comment]
> Thanks for the report! Can you also confirm you are using the v0.0.17 client?

That's correct, I am using v0.0.17
![image](https://user-images.githubusercontent.com/44410798/152190006-dce40e3f-374c-4eef-a63a-ee9227609642.png)

**Comment by maxidorius** [comment]
Thank you for the report, I'll have a look soon enough!

**Comment by MudDev** [comment]
This sounds great! Thank you!
